### ISSUE TITLE
FR05d The system should store the model in some way.  Keras default is h5, so we may use this

### ISSUE THREAD

**Issue by remoford** [starfys/timechange#44]
The system should store the model in some way.  Keras default is h5, so we may use this
Must

**Comment by remoford** [comment]
Should we be storing this model on disk and not just in memory? Current version has a subdirectory for the model but puts nothing in there...

**Comment by starfys** [comment]
We have timechange.save_model and timechange.load_model, which saves the model's weights to a file.

**Comment by remoford** [comment]
Can we add a call to save model on model generation and a call to load model to the timechance constructor when loading an existing project?

**Comment by jordanflowers** [comment]
Commit finished.
