### ISSUE TITLE
FR03d Mutable conversion parameters

### ISSUE THREAD

**Issue by remoford** [starfys/timechange#49]
The system should offer users ability to specify parameters needed for conversion in FR03a. For example, information about desired window length, overlap ratio, and sampling rate
Must

**Comment by remoford** [comment]
https://github.com/starfys/timechange/issues/30

We had a thing in the gui that kind of did this but it had some issues and was in the wrong place so is currently commented out. Should be easy enough to bring the functionality back as a new tab.

**Comment by starfys** [comment]
Used @interceptnet's code and implemented this in #57
