### ISSUE TITLE
FR03e The system should allow conversion of the data to images with no transformations applied

### ISSUE THREAD

**Issue by remoford** [starfys/timechange#50]
The system should allow conversion of the data to images with no transformations applied, just raw data
Want

**Comment by remoford** [comment]
Our current process does exactly this right?

**Comment by starfys** [comment]
(note) this one was added by me. The purpose of this was to have an image that is a direct representation of the data, without any FFT. Might be something to add later.

**Comment by starfys** [comment]
I implemented this in #57
